# Generated by Django 3.2 on 2021-04-20 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210414_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.post')),
            ],
        ),
    ]
